# Generated by Django 3.2.16 on 2022-12-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20221211_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_limit',
            field=models.DateTimeField(null=True),
        ),
    ]
