# Generated by Django 4.1.4 on 2023-01-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_date_limit_post_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='collaborators',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
