# Generated by Django 4.1.4 on 2023-01-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_title_task_name_remove_post_subtask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('in_revision', 'In Revision')], default='todo', max_length=20)),
            ],
        ),
    ]
